dist: xenial
language: node_js
sudo: false
node_js:
      - 8
      - 10
  
cache:
  directories:
    - node_modules

branches:
  except:
  - "/^renovate\\/.+$/"

# We need to use yarn to use lerna #yakshaving
install:
  - yarn global add lerna
  - yarn
script:
  yarn test

